name: CICD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image contabilix
        run: docker build -t rafaelbrunof/contabilix .
      - name: Publish image to docker hub
        run: docker push rafaelbrunof/contabilix:latest
      - name: Build docker image frontend
        run: docker build -t rafaelbrunof/frontend ./frontend
      - name: Publish image to docker hub
        run: docker push rafaelbrunof/frontend:latest

  deploy:
    needs: build
    runs-on: [ec2-user]
    steps:
      - name: Pull Contabilix Server image from docker hub
        run: docker pull rafaelbrunof/contabilix:latest
      - name: Delete old container
        run: docker rm -f contabilix
      - name: Run docker container contabilix
        run: docker run -d -p 8081:8081 --name contabilix rafaelbrunof/contabilix

      - name: Pull Contabilix Frontend image from docker hub
        run: docker pull rafaelbrunof/frontend:latest
      - name: Delete old container
        run: docker rm -f frontend
      - name: Run docker container frontend
        run: docker run -d -p 8080:80 --name frontend rafaelbrunof/frontend

      - name: Pull PostgreSQL image from docker hub
        run: docker pull postgres:latest
      - name: Run docker container postgres
        run: docker run -d -p 5432:5432 --name postgres -v ./scripts:/docker-entrypoint-initdb.d -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=minha_senha -e POSTGRES_DB=irpf postgres